create table CHECK_DATA_INTERFACE
(
CHECK_TABLE VARCHAR2(30),
KEY_VALUE VARCHAR2(64),
DATA_TYPE VARCHAR2(2)
);

create table CHECK_COMPARE_LOG
(
CHECK_SN	NUMBER(20),
KEY_VALUE	VARCHAR2(128),
CHECK_TABLE	VARCHAR2(30),
CHECK_TIMES	NUMBER(3),
CHECK_TYPE	VARCHAR2(1),
DATA_TYPE	varchar2(1),
FILE_TYPE varchar2(1),
DEAL_TIME	DATETIME
);

create table CHECK_REPAIR_LOG
(
CHECK_SN	Number(20),
KEY_VALUE	Varchar2(128),
CHECK_TABLE	Varchar2(30),
CHECK_TYPE	Varchar2(1),
CHECK_RESULT	Varchar2(1),
CHECK_NOTE	Varchar2(255),
IS_DEAL	Varchar2(1),
DEAL_TIME	Varchar2(20),
DATA_TYPE	varchar2(1),
FILE_TYPE	varchar2(1),
);

create table CHECK_REPAIR_LOG_HIS_201808
(
CHECK_SN	Number(20),
KEY_VALUE	Varchar2(128),
CHECK_TABLE	Varchar2(30),
CHECK_TYPE	Varchar2(1),
CHECK_RESULT	Varchar2(1),
CHECK_NOTE	Varchar2(255),
IS_DEAL	Varchar2(1),
DEAL_TIME	Varchar2(20),
DATA_TYPE	varchar2(1),
FILE_TYPE	varchar2(1),
);

create table CHECK_RELATION_CFG
(
CHECK_TABLE VARCHAR2(30),
KEY_ID VARCHAR2(64),
DBNO_KEYS VARCHAR(1),
PRKEY_ID VARCHAR2(128),
DBNO_PRKEYS VARCHAR(1)
);

create table CHECK_MAP_CFG(
CHECK_TABLE	VARCHAR2(30),
BDS_SQL	VARCHAR2(32),
BDS_KEYS VARCHAR2(64),
CHECK_SQL	VARCHAR2(32),
CHECK_KEYS VARCHAR2(64),
ADD_SQL	VARCHAR2(32),
EFF_DATE	DATE,
EXP_DATE	DATE
);

create table CHECK_CONTROL_INFO
(
QRYDB_NUMS	NUMBER(6),
CHECK_NUMS	NUMBER(6),
CHECK_MAX	NUMBER(6),
CTR_FLAG	VARCHAR(1),
EFF_DATE	DATE,
EXP_DATE	DATE
);