#!/bin/ksh

IBEAR_HOME=..
IBEAR_PATH=${IBEAR_HOME}/ibear

DCI_INCLUDE=-I${DSCI_PATH}/include
DCI_LIB=-L${DSCI_PATH}/lib/ -ldsci

XML_INCLUDE=-I${IBEAR_HOME}/xml2/include
XML_LIB=-L${IBEAR_HOME}/xml2/lib -lxml2

IBEAR_INCLUDE=-I${IBEAR_PATH}/include
IBEAR_LIB=-L${IBEAR_PATH}/lib -libear

IFILE_INCLUDE=-I${IFILE_PATH}/ifile/include
IFILE_LIB=-L${IFILE_PATH}/ifile/lib -lifile

ILOG_INCLUDE=-I${ILOG_PATH}/ilog/include
ILOG_LIB=-L${ILOG_PATH}/ilog/lib -lilog

ACCTMGR_INCLUCDE= -I${DSC_PATH}/include

IFLAGS=-DSS_64BIT_SERVER -D_REENTRANT -D_DSCI_ -D_DEBUG_INFO_ -D_PERFORMANCE_ #-D_TIME_LOG_

INCLUDE=-I. ${DCI_INCLUDE} ${ACCTMGR_INCLUCDE} ${IBEAR_INCLUDE} ${XML_INCLUDE} ${IFILE_INCLUDE} ${ILOG_INCLUDE}

LIB=-L. ${IBEAR_LIB} ${DCI_LIB} ${XML_LIB} ${IFILE_LIB} ${ILOG_LIB}

LIBORA=$(ORACLE_HOME)/lib -lpthread -lclntsh

.SUFFIXES:.cpp .o

CFLAGS = ${IFLAGS} ${INCLUDE}

#CC=aCC -AA +DD64 -mt -lm -g -D_LARGEFILE64_SOURCE  -D_XOPEN_SOURCE_EXTENDED -Wl,+s -Wl,+n +DSblended +z +p +inst_implicit_include 
CC=g++ -m64 -g  -lpthread  -ldl -O0 -fpermissive

