CREATE TABLE MYTEST(
MSISDN  VARCHAR(15),
FAV_BRAND       VARCHAR(2),
FAV_BIG_TYPE    VARCHAR(2),
FAV_TYPE        VARCHAR(4),
FLAG_CODE       VARCHAR(10),
FAV_ORDER       VARCHAR(1),
FAV_PERIOD      VARCHAR(1),
FREE_VALUE      NUMERIC(9),
START_TIME      DATE,
END_TIME        DATE,
GROUP_ID        VARCHAR(15),
PRODUCT_CODE    VARCHAR(8),
PRIMARY KEY(MSISDN,FAV_TYPE,FLAG_CODE,FAV_BIG_TYPE,START_TIME)
);
CREATE INDEX IND_MYTEST ON MYTEST(MSISDN);


